# services:
#   frontend:
#     image: node:21.5.0
#     container_name: hair-salon-frontend
#     working_dir: /app
#     volumes:
#       - ./hair-salon-frontend-serori:/app
#     ports:
#       - "3000:3000"
#     environment:
#       - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
#       - NEXT_PUBLIC_BACKEND_IMG_URL=http://localhost:8000/storage
#     command: npm run dev

#   backend:
#     image: php:8.2-apache
#     container_name: hair-salon-backend
#     working_dir: /var/www/html
#     volumes:
#       - ./hair-salon-backend-serori:/var/www/html
#     ports:
#       - "8000:80"
#     environment:
#       - APP_ENV=local
#       - APP_DEBUG=true
#       - APP_URL=http://localhost
#       - FRONTEND_URL=http://localhost:3000
#       - LOG_CHANNEL=stack
#       - SESSION_DRIVER=database
#       - CACHE_DRIVER=database
#       - SESSION_CONNECTION=mysql
#       - SESSION_STORE=database
#       - SESSION_DOMAIN=localhost
#       - SESSION_SECURE_COOKIE=true
#       - SESSION_LIFETIME=120
#       - SANCTUM_STATEFUL_DOMAINS=localhost:3000
#       - REACT_APP_ENCRYPTION_KEY=_serori@fire_hairsalon+app_
#       - REACT_APP_OWNER_ROLE=o_w@_seR_ori_N_N_EbR
#       - REACT_APP_MANAGER_ROLE=M_an@aSe_ro_ri_a_@gEr
#       - REACT_APP_STAFF_ROLE=S_taf@F@_seR_@_Ri@
#       - OWNER_ROLE=o_w@_seR_ori_N_N_EbR
#       - MANAGER_ROLE=M_an@aSe_ro_ri_a_@gEr
#       - STAFF_ROLE=S_taf@F@_seR_@_Ri@
#       - DB_CONNECTION=mysql
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=homestead
#       - DB_USERNAME=root
#       - DB_PASSWORD=root
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: homestead
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
