# services:
#   web:
#     image: php:8.2-apache
#     ports:
#       - "8080:80"
#     environment:
#       - APACHE_DOCUMENT_ROOT=/var/www/html/public
#     volumes:
#       - ./hair-salon-backend-serori:/var/www/html
#       - ./hair-salon-backend-serori/.env:/var/www/html/.env
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7

#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: hair_salon
#       MYSQL_USER: serori
#       MYSQL_PASSWORD: password
#     volumes:
#       - ./db:/var/lib/mysql

#   frontend:
#     build:
#       context: ./hair-salon-frontend-serori
#     ports:
#       - "3000:3000"
#     working_dir: /usr/src/app
#     volumes:
#       - ./hair-salon-frontend-serori:/usr/src/app
#     depends_on:
#       - web


