version: 2.1

executors:
  frontend-executor:
    docker:
      - image: cimg/node:21.5.0
    working_directory: ~/HairSalonApp-serori/hair-salon-frontend-serori

  backend-executor:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/HairSalonApp-serori/hair-salon-backend-serori

jobs:
  build-frontend:
    executor: frontend-executor
    steps:
      - checkout:
          path: ~/HairSalonApp-serori
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build frontend
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/HairSalonApp-serori/hair-salon-frontend-serori
          paths:
            - .next
            - public

  build-backend:
    executor: backend-executor
    steps:
      - checkout:
          path: ~/HairSalonApp-serori
      - run:
          name: Install dependencies
          command: |
            composer install
      - persist_to_workspace:
          root: ~/HairSalonApp-serori/hair-salon-backend-serori
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: ~/HairSalonApp-serori
      - setup_remote_docker:
          version: 20.10.24
      - attach_workspace:
          at: ~/HairSalonApp-serori
      - run:
          name: Login to Heroku Container Registry
          command: |
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
      - run:
          name: Deploy to Heroku
          command: |
            # Build and push the Docker images for the frontend and backend
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f ~/HairSalonApp-serori/Dockerfile ~/HairSalonApp-serori
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            # Release the app
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend
      - build-backend
      - deploy:
          requires:
            - build-frontend
            - build-backend
