# フロントエンド用のステージ
FROM node:22.5.1-alpine AS frontend

# 環境変数の設定
ENV NEXT_PUBLIC_BACKEND_URL=https://hairsalon-api.seroriman.com
ENV NEXT_PUBLIC_BACKEND_IMG_URL=https://hairsalon-api.seroriman.com/storage

WORKDIR /app/client

COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build

# フロントエンドのビルド成果物をアーティファクトとして保存
FROM node:22.5.1-alpine AS final-frontend

WORKDIR /app/client

COPY --from=frontend /app/client /app/client

EXPOSE 3000

# Next.js アプリケーションを起動
CMD ["npm", "start"]
